id: IDFCB8C5C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T17:27:40+00:00'
last_modified: '2022-06-07T14:00:21.253901+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ1080
  title: ཟབ་ལམ་རྡོ་རྗེའི་རྣལ་འབྱོར་ཕྱག་རྒྱ་ཆེན་པོའི་གཞི་ལམ་འབྲས་བུའི་ངོ་སྤྲོད་ཡང་དག་དོན་གསལ་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '6787':
      image_group_id: I1CZ1316
      title: ''
      total_pages: 268
      order: 1
      base_file: 6787.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
