id: opecha:P001679
initial_creation_type: ocr
source_metadata:
  id: bdr:W1CZ1080
  title: ཟབ་ལམ་རྡོ་རྗེའི་རྣལ་འབྱོར་ཕྱག་རྒྱ་ཆེན་པོའི་གཞི་ལམ་འབྲས་བུའི་ངོ་སྤྲོད་ཡང་དག་དོན་གསལ་།
  volume: ''
  author: ''
