id: P001679
initial_creation_type: ocr
created_at: 24/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1CZ1080
  title: ཟབ་ལམ་རྡོ་རྗེའི་རྣལ་འབྱོར་ཕྱག་རྒྱ་ཆེན་པོའི་གཞི་ལམ་འབྲས་བུའི་ངོ་སྤྲོད་ཡང་དག་དོན་གསལ་།
  author: ''
  volumes:
    8bb4f0bf04c14faeaa34c1b4393403db:
      image_group_id: I1CZ1316
      title: ''
      volume_number: 1
      total_pages: 268
      base_file: v001.txt
